#!/usr/bin/env sh

# Description: Navigate to directory using zoxide
#
# Original authors: Marty Buchaus, Dave Snider, Tim Adler, Nick Waywood

if [ ! -p "$NNN_PIPE" ]; then
    printf 'ERROR: NNN_PIPE is not set!'
    read -r _
    exit 2
fi

odir="$(zoxide query -i --)"
printf "%s" "0c$odir" > "$NNN_PIPE"
