#!/bin/sh

layout_virtualenv() {
  local venv_path="$1"
  source ${venv_path}/bin/activate
}

# Like layout_virtualenv but location-independent
layout_virtualenvwrapper() {
  local venv_path="${PWD}/$1"
  layout_virtualenv $venv_path
}
